package rndm_access.assorteddiscoveries.config;

public class ModConfigKeys {
    public static final String ENABLE_DYED_CAMPFIRES;
    public static final String ENABLE_DYED_LANTERNS;
    public static final String ENABLE_DYED_TORCHES;
    public static final String ENABLE_ALLAY_PLUSHIE;
    public static final String ENABLE_BAT_PLUSHIE;
    public static final String ENABLE_CAMEL_PLUSHIE;
    public static final String ENABLE_CAT_PLUSHIES;
    public static final String ENABLE_CHICKEN_PLUSHIE;
    public static final String ENABLE_COW_PLUSHIE;
    public static final String ENABLE_HORSE_PLUSHIES;
    public static final String ENABLE_MOOSHROOM_PLUSHIES;
    public static final String ENABLE_OCELOT_PLUSHIE;
    public static final String ENABLE_PIG_PLUSHIE;
    public static final String ENABLE_PUFFERFISH_PLUSHIE;
    public static final String ENABLE_RABBIT_PLUSHIES;
    public static final String ENABLE_SHEEP_PLUSHIES;
    public static final String ENABLE_SQUID_PLUSHIES;
    public static final String ENABLE_STRIDER_PLUSHIES;
    public static final String ENABLE_VILLAGER_PLUSHIES;
    public static final String ENABLE_BEE_PLUSHIE;
    public static final String ENABLE_CAVE_SPIDER_PLUSHIE;
    public static final String ENABLE_ENDERMAN_PLUSHIE;
    public static final String ENABLE_PIGLIN_PLUSHIES;
    public static final String ENABLE_POLAR_BEAR_PLUSHIE;
    public static final String ENABLE_SPIDER_PLUSHIE;
    public static final String ENABLE_PALE_WOLF_PLUSHIE;
    public static final String ENABLE_BLAZE_PLUSHIE;
    public static final String ENABLE_CREEPER_PLUSHIE;
    public static final String ENABLE_GHAST_PLUSHIE;
    public static final String ENABLE_GUARDIAN_PLUSHIE;
    public static final String ENABLE_HOGLIN_PLUSHIES;
    public static final String ENABLE_ILLAGER_PLUSHIES;
    public static final String ENABLE_MAGMA_CUBE_PLUSHIE;
    public static final String ENABLE_PHANTOM_PLUSHIE;
    public static final String ENABLE_RAVAGER_PLUSHIE;
    public static final String ENABLE_SHULKER_PLUSHIE;
    public static final String ENABLE_SKELETON_PLUSHIE;
    public static final String ENABLE_SLIME_PLUSHIE;
    public static final String ENABLE_VEX_PLUSHIE;
    public static final String ENABLE_WITCH_PLUSHIE;
    public static final String ENABLE_WITHER_PLUSHIE;
    public static final String ENABLE_ZOMBIE_PLUSHIE;
    public static final String ENABLE_ZOMBIE_VILLAGER_PLUSHIES;
    public static final String ENABLE_CREAKING_PLUSHIE;
    public static final String ENABLE_WOODEN_WALLS;
    public static final String ENABLE_STRIPPED_WOODEN_WALLS;
    public static final String ENABLE_WOODEN_ROPE_LADDERS;
    public static final String ENABLE_IRON_LADDERS;
    public static final String ENABLE_BLACKSTONE_TILES;
    public static final String ENABLE_TWISTED_BLACKSTONE;
    public static final String ENABLE_TWISTED_BLACKSTONE_TILES;
    public static final String ENABLE_TWISTED_NETHERRACK;
    public static final String ENABLE_TWISTED_NETHER_BRICKS;
    public static final String ENABLE_TWISTED_POLISHED_BLACKSTONE_BRICKS;
    public static final String ENABLE_WEEPING_NETHERRACK;
    public static final String ENABLE_WEEPING_NETHER_BRICKS;
    public static final String ENABLE_WEEPING_BLACKSTONE;
    public static final String ENABLE_WEEPING_POLISHED_BLACKSTONE_BRICKS;
    public static final String ENABLE_WEEPING_BLACKSTONE_TILES;
    public static final String ENABLE_SMOKY_QUARTZ_BLOCKS;
    public static final String ENABLE_SMOKY_QUARTZ_BRICKS;
    public static final String ENABLE_SMOOTH_SMOKY_QUARTZ;
    public static final String ENABLE_QUARTZ_TILES;
    public static final String ENABLE_QUARTZ_WALLS;
    public static final String ENABLE_BAUXITE;
    public static final String ENABLE_BAUXITE_BRICKS;
    public static final String ENABLE_CRACKED_BAUXITE_BRICKS;
    public static final String ENABLE_MOSSY_BAUXITE_BRICKS;
    public static final String ENABLE_STONE_TILES;
    public static final String ENABLE_CRACKED_STONE_TILES;
    public static final String ENABLE_MOSSY_STONE_TILES;
    public static final String ENABLE_WOODCUTTER;
    public static final String ENABLE_CRACKED_STONE_BRICK_BLOCKS;
    public static final String ENABLE_WOODEN_PLANTER_BOXES;
    public static final String ENABLE_GREEN_ONIONS;
    public static final String ENABLE_NOODLE_SOUP;
    public static final String ENABLE_BLUEBERRIES;
    public static final String ENABLE_BLUEBERRY_PIE;
    public static final String ENABLE_BLUEBERRY_JUICE;
    public static final String ENABLE_SWEET_BERRY_PIE;
    public static final String ENABLE_SWEET_BERRY_JUICE;
    public static final String ENABLE_CHOCOLATE_CAKE;
    public static final String ENABLE_RED_VELVET_CAKE;
    public static final String ENABLE_FRIED_EGG;
    public static final String ENABLE_HOGLIN_STEW;
    public static final String ENABLE_FORESTS_BOUNTY;
    public static final String ENABLE_WITCHS_CRADLE_SOUP;
    public static final String ENABLE_PUDDING;
    public static final String ENABLE_CARAMEL_APPLE;
    public static final String ENABLE_NETHER_BERRIES;
    public static final String ENABLE_PURPLE_MUSHROOMS;
    public static final String ENABLE_CATTAILS;
    public static final String ENABLE_BOG_BLOSSOMS;
    public static final String ENABLE_BLOOD_KELP;
    public static final String ENABLE_ENDER_PLANTS;
    public static final String ENABLE_FOREST_CABINS;
    public static final String ENABLE_DARK_FOREST_CABINS;
    public static final String ENABLE_BIRCH_FOREST_CABINS;
    public static final String ENABLE_TAIGA_CABINS;
    public static final String ENABLE_SNOWY_TAIGA_CABINS;
    public static final String ENABLE_CRIMSON_FOREST_CABINS;
    public static final String ENABLE_WARPED_FOREST_CABINS;
    public static final String ENABLE_STONE_WALLS;
    public static final String ENABLE_CALCITE_BLOCKS;
    public static final String ENABLE_POLISHED_CALCITE;
    public static final String ENABLE_CALCITE_BRICKS;
    public static final String ENABLE_CRACKED_CALCITE_BRICKS;
    public static final String ENABLE_MOSSY_CALCITE_BRICKS;
    public static final String ENABLE_DRIPSTONE_BLOCKS;
    public static final String ENABLE_POLISHED_DRIPSTONE;
    public static final String ENABLE_DRIPSTONE_BRICKS;
    public static final String ENABLE_CRACKED_DRIPSTONE_BRICKS;
    public static final String ENABLE_MOSSY_DRIPSTONE_BRICKS;
    public static final String ENABLE_QUARTZ_BRICK_BLOCKS;

    static {
        ENABLE_DYED_CAMPFIRES = "enable_dyed_campfires";
        ENABLE_DYED_LANTERNS = "enable_dyed_lanterns";
        ENABLE_DYED_TORCHES = "enable_dyed_torches";
        ENABLE_ALLAY_PLUSHIE = "enable_allay_plushie";
        ENABLE_BAT_PLUSHIE = "enable_bat_plushie";
        ENABLE_CAMEL_PLUSHIE = "enable_camel_plushie";
        ENABLE_CAT_PLUSHIES = "enable_cat_plushies";
        ENABLE_CHICKEN_PLUSHIE = "enable_chicken_plushie";
        ENABLE_COW_PLUSHIE = "enable_cow_plushie";
        ENABLE_HORSE_PLUSHIES = "enable_horse_plushies";
        ENABLE_MOOSHROOM_PLUSHIES = "enable_mooshroom_plushies";
        ENABLE_OCELOT_PLUSHIE = "enable_ocelot_plushie";
        ENABLE_PIG_PLUSHIE = "enable_pig_plushie";
        ENABLE_PUFFERFISH_PLUSHIE = "enable_pufferfish_plushie";
        ENABLE_RABBIT_PLUSHIES = "enable_rabbit_plushies";
        ENABLE_SHEEP_PLUSHIES = "enable_sheep_plushies";
        ENABLE_SQUID_PLUSHIES = "enable_squid_plushies";
        ENABLE_STRIDER_PLUSHIES = "enable_strider_plushies";
        ENABLE_VILLAGER_PLUSHIES = "enable_villager_plushies";
        ENABLE_BEE_PLUSHIE = "enable_bee_plushie";
        ENABLE_CAVE_SPIDER_PLUSHIE = "enable_cave_spider_plushie";
        ENABLE_ENDERMAN_PLUSHIE = "enable_enderman_plushie";
        ENABLE_PIGLIN_PLUSHIES = "enable_piglin_plushies";
        ENABLE_POLAR_BEAR_PLUSHIE = "enable_polar_bear_plushie";
        ENABLE_SPIDER_PLUSHIE = "enable_spider_plushie";
        ENABLE_PALE_WOLF_PLUSHIE = "enable_pale_wolf_plushie";
        ENABLE_BLAZE_PLUSHIE = "enable_blaze_plushie";
        ENABLE_CREEPER_PLUSHIE = "enable_creeper_plushie";
        ENABLE_GHAST_PLUSHIE = "enable_ghast_plushie";
        ENABLE_GUARDIAN_PLUSHIE = "enable_guardian_plushie";
        ENABLE_HOGLIN_PLUSHIES = "enable_hoglin_plushies";
        ENABLE_ILLAGER_PLUSHIES = "enable_illager_plushies";
        ENABLE_MAGMA_CUBE_PLUSHIE = "enable_magma_cube_plushie";
        ENABLE_PHANTOM_PLUSHIE = "enable_phantom_plushie";
        ENABLE_RAVAGER_PLUSHIE = "enable_ravager_plushie";
        ENABLE_SHULKER_PLUSHIE = "enable_shulker_plushie";
        ENABLE_SKELETON_PLUSHIE = "enable_skeleton_plushie";
        ENABLE_SLIME_PLUSHIE = "enable_slime_plushie";
        ENABLE_VEX_PLUSHIE = "enable_vex_plushie";
        ENABLE_WITCH_PLUSHIE = "enable_witch_plushie";
        ENABLE_WITHER_PLUSHIE = "enable_wither_plushie";
        ENABLE_ZOMBIE_PLUSHIE = "enable_zombie_plushie";
        ENABLE_ZOMBIE_VILLAGER_PLUSHIES = "enable_zombie_villager_plushies";
        ENABLE_CREAKING_PLUSHIE = "enable_creaking_plushie";
        ENABLE_WOODEN_WALLS = "enable_wooden_walls";
        ENABLE_STRIPPED_WOODEN_WALLS = "enable_stripped_wooden_walls";
        ENABLE_WOODEN_ROPE_LADDERS = "enable_wooden_rope_ladders";
        ENABLE_IRON_LADDERS = "enable_iron_ladders";
        ENABLE_BLACKSTONE_TILES = "enable_blackstone_tiles";
        ENABLE_TWISTED_BLACKSTONE = "enable_twisted_blackstone";
        ENABLE_TWISTED_BLACKSTONE_TILES = "enable_twisted_blackstone_tiles";
        ENABLE_TWISTED_NETHERRACK = "enable_twisted_netherrack";
        ENABLE_TWISTED_NETHER_BRICKS = "enable_twisted_nether_bricks";
        ENABLE_TWISTED_POLISHED_BLACKSTONE_BRICKS = "enable_twisted_polished_blackstone_bricks";
        ENABLE_WEEPING_NETHERRACK = "enable_weeping_netherrack";
        ENABLE_WEEPING_NETHER_BRICKS = "enable_weeping_nether_bricks";
        ENABLE_WEEPING_BLACKSTONE = "enable_weeping_blackstone";
        ENABLE_WEEPING_POLISHED_BLACKSTONE_BRICKS = "enable_weeping_polished_blackstone_bricks";
        ENABLE_WEEPING_BLACKSTONE_TILES = "enable_weeping_blackstone_tiles";
        ENABLE_SMOKY_QUARTZ_BLOCKS = "enable_smoky_quartz_blocks";
        ENABLE_SMOKY_QUARTZ_BRICKS = "enable_smoky_quartz_bricks";
        ENABLE_SMOOTH_SMOKY_QUARTZ = "enable_smooth_smoky_quartz";
        ENABLE_QUARTZ_TILES = "enable_quartz_tiles";
        ENABLE_QUARTZ_WALLS = "enable_quartz_walls";
        ENABLE_BAUXITE = "enable_bauxite";
        ENABLE_BAUXITE_BRICKS = "enable_bauxite_bricks";
        ENABLE_CRACKED_BAUXITE_BRICKS = "enable_cracked_bauxite_bricks";
        ENABLE_MOSSY_BAUXITE_BRICKS = "enable_mossy_bauxite_bricks";
        ENABLE_STONE_TILES = "enable_stone_tiles";
        ENABLE_CRACKED_STONE_TILES = "enable_cracked_stone_tiles";
        ENABLE_MOSSY_STONE_TILES = "enable_mossy_stone_tiles";
        ENABLE_WOODCUTTER = "enable_woodcutter";
        ENABLE_CRACKED_STONE_BRICK_BLOCKS = "enable_cracked_stone_brick_blocks";
        ENABLE_WOODEN_PLANTER_BOXES = "enable_wooden_planter_boxes";
        ENABLE_GREEN_ONIONS = "enable_green_onions";
        ENABLE_NOODLE_SOUP = "enable_noodle_soup";
        ENABLE_BLUEBERRIES = "enable_blueberries";
        ENABLE_BLUEBERRY_PIE = "enable_blueberry_pie";
        ENABLE_BLUEBERRY_JUICE = "enable_blueberry_juice";
        ENABLE_SWEET_BERRY_PIE = "enable_sweet_berry_pie";
        ENABLE_SWEET_BERRY_JUICE = "enable_sweet_berry_juice";
        ENABLE_CHOCOLATE_CAKE = "enable_chocolate_cake";
        ENABLE_RED_VELVET_CAKE = "enable_red_velvet_cake";
        ENABLE_FRIED_EGG = "enable_fried_egg";
        ENABLE_HOGLIN_STEW = "enable_hoglin_stew";
        ENABLE_FORESTS_BOUNTY = "enable_forests_bounty";
        ENABLE_WITCHS_CRADLE_SOUP = "enable_witchs_cradle_soup";
        ENABLE_PUDDING = "enable_pudding";
        ENABLE_CARAMEL_APPLE = "enable_caramel_apple";
        ENABLE_NETHER_BERRIES = "enable_nether_berries";
        ENABLE_PURPLE_MUSHROOMS = "enable_purple_mushrooms";
        ENABLE_CATTAILS = "enable_cattails";
        ENABLE_BOG_BLOSSOMS = "enable_bog_blossoms";
        ENABLE_BLOOD_KELP = "enable_blood_kelp";
        ENABLE_ENDER_PLANTS = "enable_ender_plants";
        ENABLE_FOREST_CABINS = "enable_forest_cabins";
        ENABLE_DARK_FOREST_CABINS = "enable_dark_forest_cabins";
        ENABLE_BIRCH_FOREST_CABINS = "enable_birch_forest_cabins";
        ENABLE_TAIGA_CABINS = "enable_taiga_cabins";
        ENABLE_SNOWY_TAIGA_CABINS = "enable_snowy_taiga_cabins";
        ENABLE_CRIMSON_FOREST_CABINS = "enable_crimson_forest_cabins";
        ENABLE_WARPED_FOREST_CABINS = "enable_warped_forest_cabins";
        ENABLE_STONE_WALLS = "enable_stone_walls";
        ENABLE_CALCITE_BLOCKS = "enable_calcite_blocks";
        ENABLE_POLISHED_CALCITE = "enable_polished_calcite";
        ENABLE_CALCITE_BRICKS = "enable_calcite_bricks";
        ENABLE_CRACKED_CALCITE_BRICKS = "enable_cracked_calcite_bricks";
        ENABLE_MOSSY_CALCITE_BRICKS = "enable_mossy_calcite_bricks";
        ENABLE_DRIPSTONE_BLOCKS = "enable_dripstone_blocks";
        ENABLE_POLISHED_DRIPSTONE = "enable_polished_dripstone";
        ENABLE_DRIPSTONE_BRICKS = "enable_dripstone_bricks";
        ENABLE_CRACKED_DRIPSTONE_BRICKS = "enable_cracked_dripstone_bricks";
        ENABLE_MOSSY_DRIPSTONE_BRICKS = "enable_mossy_dripstone_bricks";
        ENABLE_QUARTZ_BRICK_BLOCKS = "enable_quartz_brick_blocks";
    }
}
