package rndm_access.assorteddiscoveries.core;

import net.minecraft.block.Block;
import net.minecraft.item.*;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.math.Direction;
import rndm_access.assorteddiscoveries.ADReference;
import rndm_access.assorteddiscoveries.AssortedDiscoveries;
import rndm_access.assorteddiscoveries.item.*;

public class ADItems {
    public static final Item BAT_PLUSH = blockItem(ADBlocks.BAT_PLUSH);
    public static final Item BLAZE_PLUSH = blockItem(ADBlocks.BLAZE_PLUSH);
    public static final Item CAVE_SPIDER_PLUSH = blockItem(ADBlocks.CAVE_SPIDER_PLUSH);
    public static final Item CHICKEN_PLUSH = blockItem(ADBlocks.CHICKEN_PLUSH);
    public static final Item COW_PLUSH = blockItem(ADBlocks.COW_PLUSH);
    public static final Item CREEPER_PLUSH = blockItem(ADBlocks.CREEPER_PLUSH);
    public static final Item ENDERMAN_PLUSH = blockItem(ADBlocks.ENDERMAN_PLUSH);
    public static final Item GHAST_PLUSH = blockItem(ADBlocks.GHAST_PLUSH);
    public static final Item GUARDIAN_PLUSH = blockItem(ADBlocks.GUARDIAN_PLUSH);
    public static final Item WHITE_HORSE_PLUSH = blockItem(ADBlocks.WHITE_HORSE_PLUSH);
    public static final Item GRAY_HORSE_PLUSH = blockItem(ADBlocks.GRAY_HORSE_PLUSH);
    public static final Item LIGHT_GRAY_HORSE_PLUSH = blockItem(ADBlocks.LIGHT_GRAY_HORSE_PLUSH);
    public static final Item BROWN_HORSE_PLUSH = blockItem(ADBlocks.BROWN_HORSE_PLUSH);
    public static final Item BLACK_HORSE_PLUSH = blockItem(ADBlocks.BLACK_HORSE_PLUSH);
    public static final Item MAGMA_CUBE_PLUSH = blockItem(ADBlocks.MAGMA_CUBE_PLUSH);
    public static final Item RED_MOOSHROOM_PLUSH = blockItem(ADBlocks.RED_MOOSHROOM_PLUSH);
    public static final Item BROWN_MOOSHROOM_PLUSH = blockItem(ADBlocks.BROWN_MOOSHROOM_PLUSH);
    public static final Item OCELOT_PLUSH = blockItem(ADBlocks.OCELOT_PLUSH);
    public static final Item TABBY_CAT_PLUSH = blockItem(ADBlocks.TABBY_CAT_PLUSH);
    public static final Item TUXEDO_CAT_PLUSH = blockItem(ADBlocks.TUXEDO_CAT_PLUSH);
    public static final Item RED_CAT_PLUSH = blockItem(ADBlocks.RED_CAT_PLUSH);
    public static final Item SIAMESE_CAT_PLUSH = blockItem(ADBlocks.SIAMESE_CAT_PLUSH);
    public static final Item BRITISH_SHORTHAIR_CAT_PLUSH = blockItem(ADBlocks.BRITISH_SHORTHAIR_CAT_PLUSH);
    public static final Item CALICO_CAT_PLUSH = blockItem(ADBlocks.CALICO_CAT_PLUSH);
    public static final Item PERSIAN_CAT_PLUSH = blockItem(ADBlocks.PERSIAN_CAT_PLUSH);
    public static final Item RAGDOLL_CAT_PLUSH = blockItem(ADBlocks.RAGDOLL_CAT_PLUSH);
    public static final Item WHITE_CAT_PLUSH = blockItem(ADBlocks.WHITE_CAT_PLUSH);
    public static final Item JELLIE_CAT_PLUSH = blockItem(ADBlocks.JELLIE_CAT_PLUSH);
    public static final Item BLACK_CAT_PLUSH = blockItem(ADBlocks.BLACK_CAT_PLUSH);
    public static final Item PIG_PLUSH = blockItem(ADBlocks.PIG_PLUSH);
    public static final Item BROWN_RABBIT_PLUSH = blockItem(ADBlocks.BROWN_RABBIT_PLUSH);
    public static final Item WHITE_RABBIT_PLUSH = blockItem(ADBlocks.WHITE_RABBIT_PLUSH);
    public static final Item BLACK_RABBIT_PLUSH = blockItem(ADBlocks.BLACK_RABBIT_PLUSH);
    public static final Item WHITE_SPLOTCHED_RABBIT_PLUSH = blockItem(ADBlocks.WHITE_SPLOTCHED_RABBIT_PLUSH);
    public static final Item GOLD_RABBIT_PLUSH = blockItem(ADBlocks.GOLD_RABBIT_PLUSH);
    public static final Item TOAST_RABBIT_PLUSH = blockItem(ADBlocks.TOAST_RABBIT_PLUSH);
    public static final Item SALT_RABBIT_PLUSH = blockItem(ADBlocks.SALT_RABBIT_PLUSH);
    public static final Item WHITE_SHEEP_PLUSH = blockItem(ADBlocks.WHITE_SHEEP_PLUSH);
    public static final Item ORANGE_SHEEP_PLUSH = blockItem(ADBlocks.ORANGE_SHEEP_PLUSH);
    public static final Item MAGENTA_SHEEP_PLUSH = blockItem(ADBlocks.MAGENTA_SHEEP_PLUSH);
    public static final Item LIGHT_BLUE_SHEEP_PLUSH = blockItem(ADBlocks.LIGHT_BLUE_SHEEP_PLUSH);
    public static final Item YELLOW_SHEEP_PLUSH = blockItem(ADBlocks.YELLOW_SHEEP_PLUSH);
    public static final Item LIME_SHEEP_PLUSH = blockItem(ADBlocks.LIME_SHEEP_PLUSH);
    public static final Item PINK_SHEEP_PLUSH = blockItem(ADBlocks.PINK_SHEEP_PLUSH);
    public static final Item GRAY_SHEEP_PLUSH = blockItem(ADBlocks.GRAY_SHEEP_PLUSH);
    public static final Item LIGHT_GRAY_SHEEP_PLUSH = blockItem(ADBlocks.LIGHT_GRAY_SHEEP_PLUSH);
    public static final Item CYAN_SHEEP_PLUSH = blockItem(ADBlocks.CYAN_SHEEP_PLUSH);
    public static final Item PURPLE_SHEEP_PLUSH = blockItem(ADBlocks.PURPLE_SHEEP_PLUSH);
    public static final Item BLUE_SHEEP_PLUSH = blockItem(ADBlocks.BLUE_SHEEP_PLUSH);
    public static final Item BROWN_SHEEP_PLUSH = blockItem(ADBlocks.BROWN_SHEEP_PLUSH);
    public static final Item GREEN_SHEEP_PLUSH = blockItem(ADBlocks.GREEN_SHEEP_PLUSH);
    public static final Item RED_SHEEP_PLUSH = blockItem(ADBlocks.RED_SHEEP_PLUSH);
    public static final Item BLACK_SHEEP_PLUSH = blockItem(ADBlocks.BLACK_SHEEP_PLUSH);
    public static final Item MAROON_SHEEP_PLUSH = blockItem(ADBlocks.MAROON_SHEEP_PLUSH);
    public static final Item SKELETON_PLUSH = blockItem(ADBlocks.SKELETON_PLUSH);
    public static final Item SLIME_PLUSH = blockItem(ADBlocks.SLIME_PLUSH);
    public static final Item SPIDER_PLUSH = blockItem(ADBlocks.SPIDER_PLUSH);
    public static final Item SQUID_PLUSH = blockItem(ADBlocks.SQUID_PLUSH);
    public static final Item GLOW_SQUID_PLUSH = blockItem(ADBlocks.GLOW_SQUID_PLUSH);
    public static final Item BEE_PLUSH = blockItem(ADBlocks.BEE_PLUSH);
    public static final Item PLAINS_VILLAGER_PLUSH = blockItem(ADBlocks.PLAINS_VILLAGER_PLUSH);
    public static final Item DESERT_VILLAGER_PLUSH = blockItem(ADBlocks.DESERT_VILLAGER_PLUSH);
    public static final Item JUNGLE_VILLAGER_PLUSH = blockItem(ADBlocks.JUNGLE_VILLAGER_PLUSH);
    public static final Item SAVANNA_VILLAGER_PLUSH = blockItem(ADBlocks.SAVANNA_VILLAGER_PLUSH);
    public static final Item SNOW_VILLAGER_PLUSH = blockItem(ADBlocks.SNOW_VILLAGER_PLUSH);
    public static final Item SWAMP_VILLAGER_PLUSH = blockItem(ADBlocks.SWAMP_VILLAGER_PLUSH);
    public static final Item TAIGA_VILLAGER_PLUSH = blockItem(ADBlocks.TAIGA_VILLAGER_PLUSH);
    public static final Item CRIMSON_VILLAGER_PLUSH = blockItem(ADBlocks.CRIMSON_VILLAGER_PLUSH);
    public static final Item WARPED_VILLAGER_PLUSH = blockItem(ADBlocks.WARPED_VILLAGER_PLUSH);
    public static final Item WANDERING_TRADER_PLUSH = blockItem(ADBlocks.WANDERING_TRADER_PLUSH);
    public static final Item PLAINS_ZOMBIE_VILLAGER_PLUSH = blockItem(ADBlocks.PLAINS_ZOMBIE_VILLAGER_PLUSH);
    public static final Item DESERT_ZOMBIE_VILLAGER_PLUSH = blockItem(ADBlocks.DESERT_ZOMBIE_VILLAGER_PLUSH);
    public static final Item JUNGLE_ZOMBIE_VILLAGER_PLUSH = blockItem(ADBlocks.JUNGLE_ZOMBIE_VILLAGER_PLUSH);
    public static final Item SAVANNA_ZOMBIE_VILLAGER_PLUSH = blockItem(ADBlocks.SAVANNA_ZOMBIE_VILLAGER_PLUSH);
    public static final Item SNOW_ZOMBIE_VILLAGER_PLUSH = blockItem(ADBlocks.SNOW_ZOMBIE_VILLAGER_PLUSH);
    public static final Item SWAMP_ZOMBIE_VILLAGER_PLUSH = blockItem(ADBlocks.SWAMP_ZOMBIE_VILLAGER_PLUSH);
    public static final Item TAIGA_ZOMBIE_VILLAGER_PLUSH = blockItem(ADBlocks.TAIGA_ZOMBIE_VILLAGER_PLUSH);
    public static final Item CRIMSON_ZOMBIE_VILLAGER_PLUSH = blockItem(ADBlocks.CRIMSON_ZOMBIE_VILLAGER_PLUSH);
    public static final Item WARPED_ZOMBIE_VILLAGER_PLUSH = blockItem(ADBlocks.WARPED_ZOMBIE_VILLAGER_PLUSH);
    public static final Item WITCH_PLUSH = blockItem(ADBlocks.WITCH_PLUSH);
    public static final Item WOLF_PLUSH = blockItem(ADBlocks.WOLF_PLUSH);
    public static final Item ZOMBIE_PLUSH = blockItem(ADBlocks.ZOMBIE_PLUSH);
    public static final Item PIGLIN_PLUSH = blockItem(ADBlocks.PIGLIN_PLUSH);
    public static final Item ZOMBIFIED_PIGLIN_PLUSH = blockItem(ADBlocks.ZOMBIFIED_PIGLIN_PLUSH);
    public static final Item PUFFERFISH_PLUSH = blockItem(ADBlocks.PUFFERFISH_PLUSH);
    public static final Item WITHER_PLUSH = blockItem(ADBlocks.WITHER_PLUSH);
    public static final Item STRIDER_PLUSH = blockItem(ADBlocks.STRIDER_PLUSH);
    public static final Item SHIVERING_STRIDER_PLUSH = blockItem(ADBlocks.SHIVERING_STRIDER_PLUSH);
    public static final Item PHANTOM_PLUSH = blockItem(ADBlocks.PHANTOM_PLUSH);
    public static final Item HOGLIN_PLUSH = blockItem(ADBlocks.HOGLIN_PLUSH);
    public static final Item ZOGLIN_PLUSH = blockItem(ADBlocks.ZOGLIN_PLUSH);
    public static final Item POLAR_BEAR_PLUSH = blockItem(ADBlocks.POLAR_BEAR_PLUSH);
    public static final Item ALLAY_PLUSH = blockItem(ADBlocks.ALLAY_PLUSH);
    public static final Item PILLAGER_PLUSH = blockItem(ADBlocks.PILLAGER_PLUSH);
    public static final Item VINDICATOR_PLUSH = blockItem(ADBlocks.VINDICATOR_PLUSH);
    public static final Item EVOKER_PLUSH = blockItem(ADBlocks.EVOKER_PLUSH);
    public static final Item RAVAGER_PLUSH = blockItem(ADBlocks.RAVAGER_PLUSH);
    public static final Item SHULKER_PLUSH = blockItem(ADBlocks.SHULKER_PLUSH);
    public static final Item VEX_PLUSH = blockItem(ADBlocks.VEX_PLUSH);
    public static final Item NETHER_SMOKY_QUARTZ_ORE = blockItem(ADBlocks.NETHER_SMOKY_QUARTZ_ORE);
    public static final Item SMOKY_QUARTZ_BLOCK = blockItem(ADBlocks.SMOKY_QUARTZ_BLOCK);
    public static final Item CHISELED_SMOKY_QUARTZ_BLOCK = blockItem(ADBlocks.CHISELED_SMOKY_QUARTZ_BLOCK);
    public static final Item SMOKY_QUARTZ_BRICKS = blockItem(ADBlocks.SMOKY_QUARTZ_BRICKS);
    public static final Item SMOKY_QUARTZ_BRICK_STAIRS = blockItem(ADBlocks.SMOKY_QUARTZ_BRICK_STAIRS);
    public static final Item SMOKY_QUARTZ_BRICK_SLAB = blockItem(ADBlocks.SMOKY_QUARTZ_BRICK_SLAB);
    public static final Item SMOKY_QUARTZ_BRICK_WALL = blockItem(ADBlocks.SMOKY_QUARTZ_BRICK_WALL);
    public static final Item SMOKY_QUARTZ_PILLAR = blockItem(ADBlocks.SMOKY_QUARTZ_PILLAR);
    public static final Item SMOKY_QUARTZ_STAIRS = blockItem(ADBlocks.SMOKY_QUARTZ_STAIRS);
    public static final Item SMOKY_QUARTZ_SLAB = blockItem(ADBlocks.SMOKY_QUARTZ_SLAB);
    public static final Item SMOKY_QUARTZ_WALL = blockItem(ADBlocks.SMOKY_QUARTZ_WALL);
    public static final Item SMOOTH_SMOKY_QUARTZ = blockItem(ADBlocks.SMOOTH_SMOKY_QUARTZ);
    public static final Item SMOOTH_SMOKY_QUARTZ_STAIRS = blockItem(ADBlocks.SMOOTH_SMOKY_QUARTZ_STAIRS);
    public static final Item SMOOTH_SMOKY_QUARTZ_SLAB = blockItem(ADBlocks.SMOOTH_SMOKY_QUARTZ_SLAB);
    public static final Item SMOOTH_SMOKY_QUARTZ_WALL = blockItem(ADBlocks.SMOOTH_SMOKY_QUARTZ_WALL);
    public static final Item CRACKED_STONE_BRICK_STAIRS = blockItem(ADBlocks.CRACKED_STONE_BRICK_STAIRS);
    public static final Item CRACKED_STONE_BRICK_SLAB = blockItem(ADBlocks.CRACKED_STONE_BRICK_SLAB);
    public static final Item CRACKED_STONE_BRICK_WALL = blockItem(ADBlocks.CRACKED_STONE_BRICK_WALL);
    public static final Item OAK_PLANTER_BOX = blockItem(ADBlocks.OAK_PLANTER_BOX);
    public static final Item SPRUCE_PLANTER_BOX = blockItem(ADBlocks.SPRUCE_PLANTER_BOX);
    public static final Item BIRCH_PLANTER_BOX = blockItem(ADBlocks.BIRCH_PLANTER_BOX);
    public static final Item JUNGLE_PLANTER_BOX = blockItem(ADBlocks.JUNGLE_PLANTER_BOX);
    public static final Item ACACIA_PLANTER_BOX = blockItem(ADBlocks.ACACIA_PLANTER_BOX);
    public static final Item DARK_OAK_PLANTER_BOX = blockItem(ADBlocks.DARK_OAK_PLANTER_BOX);
    public static final Item MANGROVE_PLANTER_BOX = blockItem(ADBlocks.MANGROVE_PLANTER_BOX);
    public static final Item CHERRY_PLANTER_BOX = blockItem(ADBlocks.CHERRY_PLANTER_BOX);
    public static final Item CRIMSON_PLANTER_BOX = blockItem(ADBlocks.CRIMSON_PLANTER_BOX);
    public static final Item WARPED_PLANTER_BOX = blockItem(ADBlocks.WARPED_PLANTER_BOX);
    public static final Item OAK_WALL = blockItem(ADBlocks.OAK_WALL);
    public static final Item SPRUCE_WALL = blockItem(ADBlocks.SPRUCE_WALL);
    public static final Item BIRCH_WALL = blockItem(ADBlocks.BIRCH_WALL);
    public static final Item JUNGLE_WALL = blockItem(ADBlocks.JUNGLE_WALL);
    public static final Item ACACIA_WALL = blockItem(ADBlocks.ACACIA_WALL);
    public static final Item DARK_OAK_WALL = blockItem(ADBlocks.DARK_OAK_WALL);
    public static final Item MANGROVE_WALL = blockItem(ADBlocks.MANGROVE_WALL);
    public static final Item CRIMSON_WALL = blockItem(ADBlocks.CRIMSON_WALL);
    public static final Item WARPED_WALL = blockItem(ADBlocks.WARPED_WALL);
    public static final Item CHERRY_WALL = blockItem(ADBlocks.CHERRY_WALL);
    public static final Item STRIPPED_OAK_WALL = blockItem(ADBlocks.STRIPPED_OAK_WALL);
    public static final Item STRIPPED_SPRUCE_WALL = blockItem(ADBlocks.STRIPPED_SPRUCE_WALL);
    public static final Item STRIPPED_BIRCH_WALL = blockItem(ADBlocks.STRIPPED_BIRCH_WALL);
    public static final Item STRIPPED_JUNGLE_WALL = blockItem(ADBlocks.STRIPPED_JUNGLE_WALL);
    public static final Item STRIPPED_ACACIA_WALL = blockItem(ADBlocks.STRIPPED_ACACIA_WALL);
    public static final Item STRIPPED_DARK_OAK_WALL = blockItem(ADBlocks.STRIPPED_DARK_OAK_WALL);
    public static final Item STRIPPED_MANGROVE_WALL = blockItem(ADBlocks.STRIPPED_MANGROVE_WALL);
    public static final Item STRIPPED_CRIMSON_WALL = blockItem(ADBlocks.STRIPPED_CRIMSON_WALL);
    public static final Item STRIPPED_WARPED_WALL = blockItem(ADBlocks.STRIPPED_WARPED_WALL);
    public static final Item STRIPPED_CHERRY_WALL = blockItem(ADBlocks.STRIPPED_CHERRY_WALL);
    public static final Item OAK_ROPE_LADDER = ropeLadderBlockItem(ADBlocks.OAK_ROPE_LADDER);
    public static final Item SPRUCE_ROPE_LADDER = ropeLadderBlockItem(ADBlocks.SPRUCE_ROPE_LADDER);
    public static final Item BIRCH_ROPE_LADDER = ropeLadderBlockItem(ADBlocks.BIRCH_ROPE_LADDER);
    public static final Item JUNGLE_ROPE_LADDER = ropeLadderBlockItem(ADBlocks.JUNGLE_ROPE_LADDER);
    public static final Item ACACIA_ROPE_LADDER = ropeLadderBlockItem(ADBlocks.ACACIA_ROPE_LADDER);
    public static final Item DARK_OAK_ROPE_LADDER = ropeLadderBlockItem(ADBlocks.DARK_OAK_ROPE_LADDER);
    public static final Item CRIMSON_ROPE_LADDER = ropeLadderBlockItem(ADBlocks.CRIMSON_ROPE_LADDER);
    public static final Item WARPED_ROPE_LADDER = ropeLadderBlockItem(ADBlocks.WARPED_ROPE_LADDER);
    public static final Item MANGROVE_ROPE_LADDER = ropeLadderBlockItem(ADBlocks.MANGROVE_ROPE_LADDER);
    public static final Item CHERRY_ROPE_LADDER = ropeLadderBlockItem(ADBlocks.CHERRY_ROPE_LADDER);
    public static final Item IRON_LADDER = blockItem(ADBlocks.IRON_LADDER);
    public static final Item SNOW_BRICKS = blockItem(ADBlocks.SNOW_BRICKS);
    public static final Item SNOW_BRICK_STAIRS = blockItem(ADBlocks.SNOW_BRICK_STAIRS);
    public static final Item SNOW_BRICK_SLAB = blockItem(ADBlocks.SNOW_BRICK_SLAB);
    public static final Item SNOW_BRICK_WALL = blockItem(ADBlocks.SNOW_BRICK_WALL);
    public static final Item PACKED_SNOW = blockItem(ADBlocks.PACKED_SNOW);
    public static final Item PACKED_SNOW_STAIRS = blockItem(ADBlocks.PACKED_SNOW_STAIRS);
    public static final Item PACKED_SNOW_SLAB = blockItem(ADBlocks.PACKED_SNOW_SLAB);
    public static final Item PACKED_SNOW_WALL = blockItem(ADBlocks.PACKED_SNOW_WALL);
    public static final Item PURPLE_MUSHROOM = blockItem(ADBlocks.PURPLE_MUSHROOM);
    public static final Item PURPLE_MUSHROOM_BLOCK = blockItem(ADBlocks.PURPLE_MUSHROOM_BLOCK);
    public static final Item WOODCUTTER = blockItem(ADBlocks.WOODCUTTER);
    public static final Item WHITE_CAMPFIRE = blockItem(ADBlocks.WHITE_CAMPFIRE);
    public static final Item ORANGE_CAMPFIRE = blockItem(ADBlocks.ORANGE_CAMPFIRE);
    public static final Item MAGENTA_CAMPFIRE = blockItem(ADBlocks.MAGENTA_CAMPFIRE);
    public static final Item LIGHT_BLUE_CAMPFIRE = blockItem(ADBlocks.LIGHT_BLUE_CAMPFIRE);
    public static final Item YELLOW_CAMPFIRE = blockItem(ADBlocks.YELLOW_CAMPFIRE);
    public static final Item LIME_CAMPFIRE = blockItem(ADBlocks.LIME_CAMPFIRE);
    public static final Item PINK_CAMPFIRE = blockItem(ADBlocks.PINK_CAMPFIRE);
    public static final Item GRAY_CAMPFIRE = blockItem(ADBlocks.GRAY_CAMPFIRE);
    public static final Item LIGHT_GRAY_CAMPFIRE = blockItem(ADBlocks.LIGHT_GRAY_CAMPFIRE);
    public static final Item CYAN_CAMPFIRE = blockItem(ADBlocks.CYAN_CAMPFIRE);
    public static final Item PURPLE_CAMPFIRE = blockItem(ADBlocks.PURPLE_CAMPFIRE);
    public static final Item BLUE_CAMPFIRE = blockItem(ADBlocks.BLUE_CAMPFIRE);
    public static final Item BROWN_CAMPFIRE = blockItem(ADBlocks.BROWN_CAMPFIRE);
    public static final Item GREEN_CAMPFIRE = blockItem(ADBlocks.GREEN_CAMPFIRE);
    public static final Item RED_CAMPFIRE = blockItem(ADBlocks.RED_CAMPFIRE);
    public static final Item BLACK_CAMPFIRE = blockItem(ADBlocks.BLACK_CAMPFIRE);
    public static final Item MAROON_CAMPFIRE = blockItem(ADBlocks.MAROON_CAMPFIRE);
    public static final Item WHITE_LANTERN = blockItem(ADBlocks.WHITE_LANTERN);
    public static final Item ORANGE_LANTERN = blockItem(ADBlocks.ORANGE_LANTERN);
    public static final Item MAGENTA_LANTERN = blockItem(ADBlocks.MAGENTA_LANTERN);
    public static final Item LIGHT_BLUE_LANTERN = blockItem(ADBlocks.LIGHT_BLUE_LANTERN);
    public static final Item YELLOW_LANTERN = blockItem(ADBlocks.YELLOW_LANTERN);
    public static final Item LIME_LANTERN = blockItem(ADBlocks.LIME_LANTERN);
    public static final Item PINK_LANTERN = blockItem(ADBlocks.PINK_LANTERN);
    public static final Item GRAY_LANTERN = blockItem(ADBlocks.GRAY_LANTERN);
    public static final Item LIGHT_GRAY_LANTERN = blockItem(ADBlocks.LIGHT_GRAY_LANTERN);
    public static final Item CYAN_LANTERN = blockItem(ADBlocks.CYAN_LANTERN);
    public static final Item PURPLE_LANTERN = blockItem(ADBlocks.PURPLE_LANTERN);
    public static final Item BLUE_LANTERN = blockItem(ADBlocks.BLUE_LANTERN);
    public static final Item BROWN_LANTERN = blockItem(ADBlocks.BROWN_LANTERN);
    public static final Item GREEN_LANTERN = blockItem(ADBlocks.GREEN_LANTERN);
    public static final Item RED_LANTERN = blockItem(ADBlocks.RED_LANTERN);
    public static final Item BLACK_LANTERN = blockItem(ADBlocks.BLACK_LANTERN);
    public static final Item MAROON_LANTERN = blockItem(ADBlocks.MAROON_LANTERN);
    public static final Item WHITE_TORCH = wallStandingBlockItem(ADBlocks.WHITE_TORCH, ADBlocks.WHITE_WALL_TORCH);
    public static final Item ORANGE_TORCH = wallStandingBlockItem(ADBlocks.ORANGE_TORCH, ADBlocks.ORANGE_WALL_TORCH);
    public static final Item MAGENTA_TORCH = wallStandingBlockItem(ADBlocks.MAGENTA_TORCH, ADBlocks.MAGENTA_WALL_TORCH);
    public static final Item LIGHT_BLUE_TORCH = wallStandingBlockItem(ADBlocks.LIGHT_BLUE_TORCH, ADBlocks.LIGHT_BLUE_WALL_TORCH);
    public static final Item YELLOW_TORCH = wallStandingBlockItem(ADBlocks.YELLOW_TORCH, ADBlocks.YELLOW_WALL_TORCH);
    public static final Item LIME_TORCH = wallStandingBlockItem(ADBlocks.LIME_TORCH, ADBlocks.LIME_WALL_TORCH);
    public static final Item PINK_TORCH = wallStandingBlockItem(ADBlocks.PINK_TORCH, ADBlocks.PINK_WALL_TORCH);
    public static final Item GRAY_TORCH = wallStandingBlockItem(ADBlocks.GRAY_TORCH, ADBlocks.GRAY_WALL_TORCH);
    public static final Item LIGHT_GRAY_TORCH = wallStandingBlockItem(ADBlocks.LIGHT_GRAY_TORCH, ADBlocks.LIGHT_GRAY_WALL_TORCH);
    public static final Item CYAN_TORCH = wallStandingBlockItem(ADBlocks.CYAN_TORCH, ADBlocks.CYAN_WALL_TORCH);
    public static final Item PURPLE_TORCH = wallStandingBlockItem(ADBlocks.PURPLE_TORCH, ADBlocks.PURPLE_WALL_TORCH);
    public static final Item BLUE_TORCH = wallStandingBlockItem(ADBlocks.BLUE_TORCH, ADBlocks.BLUE_WALL_TORCH);
    public static final Item BROWN_TORCH = wallStandingBlockItem(ADBlocks.BROWN_TORCH, ADBlocks.BROWN_WALL_TORCH);
    public static final Item GREEN_TORCH = wallStandingBlockItem(ADBlocks.GREEN_TORCH, ADBlocks.GREEN_WALL_TORCH);
    public static final Item RED_TORCH = wallStandingBlockItem(ADBlocks.RED_TORCH, ADBlocks.RED_WALL_TORCH);
    public static final Item BLACK_TORCH = wallStandingBlockItem(ADBlocks.BLACK_TORCH, ADBlocks.BLACK_WALL_TORCH);
    public static final Item MAROON_TORCH = wallStandingBlockItem(ADBlocks.MAROON_TORCH, ADBlocks.MAROON_WALL_TORCH);
    public static final Item BAUXITE = blockItem(ADBlocks.BAUXITE);
    public static final Item BAUXITE_SLAB = blockItem(ADBlocks.BAUXITE_SLAB);
    public static final Item BAUXITE_STAIRS = blockItem(ADBlocks.BAUXITE_STAIRS);
    public static final Item BAUXITE_WALL = blockItem(ADBlocks.BAUXITE_WALL);
    public static final Item BAUXITE_BRICKS = blockItem(ADBlocks.BAUXITE_BRICKS);
    public static final Item BAUXITE_BRICK_STAIRS = blockItem(ADBlocks.BAUXITE_BRICK_STAIRS);
    public static final Item BAUXITE_BRICK_SLAB = blockItem(ADBlocks.BAUXITE_BRICK_SLAB);
    public static final Item BAUXITE_BRICK_WALL = blockItem(ADBlocks.BAUXITE_BRICK_WALL);
    public static final Item MOSSY_BAUXITE_BRICKS = blockItem(ADBlocks.MOSSY_BAUXITE_BRICKS);
    public static final Item MOSSY_BAUXITE_BRICK_STAIRS = blockItem(ADBlocks.MOSSY_BAUXITE_BRICK_STAIRS);
    public static final Item MOSSY_BAUXITE_BRICK_SLAB = blockItem(ADBlocks.MOSSY_BAUXITE_BRICK_SLAB);
    public static final Item MOSSY_BAUXITE_BRICK_WALL = blockItem(ADBlocks.MOSSY_BAUXITE_BRICK_WALL);
    public static final Item CRACKED_BAUXITE_BRICKS = blockItem(ADBlocks.CRACKED_BAUXITE_BRICKS);
    public static final Item CRACKED_BAUXITE_BRICK_STAIRS = blockItem(ADBlocks.CRACKED_BAUXITE_BRICK_STAIRS);
    public static final Item CRACKED_BAUXITE_BRICK_SLAB = blockItem(ADBlocks.CRACKED_BAUXITE_BRICK_SLAB);
    public static final Item CRACKED_BAUXITE_BRICK_WALL = blockItem(ADBlocks.CRACKED_BAUXITE_BRICK_WALL);
    public static final Item TWISTED_NETHER_BRICKS = blockItem(ADBlocks.TWISTED_NETHER_BRICKS);
    public static final Item TWISTED_NETHER_BRICK_STAIRS = blockItem(ADBlocks.TWISTED_NETHER_BRICK_STAIRS);
    public static final Item TWISTED_NETHER_BRICK_SLAB = blockItem(ADBlocks.TWISTED_NETHER_BRICK_SLAB);
    public static final Item TWISTED_NETHER_BRICK_WALL = blockItem(ADBlocks.TWISTED_NETHER_BRICK_WALL);
    public static final Item TWISTED_NETHERRACK = blockItem(ADBlocks.TWISTED_NETHERRACK);
    public static final Item TWISTED_NETHERRACK_STAIRS = blockItem(ADBlocks.TWISTED_NETHERRACK_STAIRS);
    public static final Item TWISTED_NETHERRACK_SLAB = blockItem(ADBlocks.TWISTED_NETHERRACK_SLAB);
    public static final Item TWISTED_NETHERRACK_WALL = blockItem(ADBlocks.TWISTED_NETHERRACK_WALL);
    public static final Item WEEPING_NETHER_BRICKS = blockItem(ADBlocks.WEEPING_NETHER_BRICKS);
    public static final Item WEEPING_NETHER_BRICK_STAIRS = blockItem(ADBlocks.WEEPING_NETHER_BRICK_STAIRS);
    public static final Item WEEPING_NETHER_BRICK_SLAB = blockItem(ADBlocks.WEEPING_NETHER_BRICK_SLAB);
    public static final Item WEEPING_NETHER_BRICK_WALL = blockItem(ADBlocks.WEEPING_NETHER_BRICK_WALL);
    public static final Item WEEPING_NETHERRACK = blockItem(ADBlocks.WEEPING_NETHERRACK);
    public static final Item WEEPING_NETHERRACK_STAIRS = blockItem(ADBlocks.WEEPING_NETHERRACK_STAIRS);
    public static final Item WEEPING_NETHERRACK_SLAB = blockItem(ADBlocks.WEEPING_NETHERRACK_SLAB);
    public static final Item WEEPING_NETHERRACK_WALL = blockItem(ADBlocks.WEEPING_NETHERRACK_WALL);
    public static final Item SNAPDRAGON = blockItem(ADBlocks.SNAPDRAGON);
    public static final Item ENDER_GRASS = blockItem(ADBlocks.ENDER_GRASS);
    public static final Item ICICLE = blockItem(ADBlocks.ICICLE);
    public static final Item CHOCOLATE_CAKE = blockItem(ADBlocks.CHOCOLATE_CAKE);
    public static final Item RED_VELVET_CAKE = blockItem(ADBlocks.RED_VELVET_CAKE);
    public static final Item STONE_TILES = blockItem(ADBlocks.STONE_TILES);
    public static final Item STONE_TILE_SLAB = blockItem(ADBlocks.STONE_TILE_SLAB);
    public static final Item STONE_TILE_STAIRS = blockItem(ADBlocks.STONE_TILE_STAIRS);
    public static final Item STONE_TILE_WALL = blockItem(ADBlocks.STONE_TILE_WALL);
    public static final Item MOSSY_STONE_TILES = blockItem(ADBlocks.MOSSY_STONE_TILES);
    public static final Item MOSSY_STONE_TILE_SLAB = blockItem(ADBlocks.MOSSY_STONE_TILE_SLAB);
    public static final Item MOSSY_STONE_TILE_STAIRS = blockItem(ADBlocks.MOSSY_STONE_TILE_STAIRS);
    public static final Item MOSSY_STONE_TILE_WALL = blockItem(ADBlocks.MOSSY_STONE_TILE_WALL);
    public static final Item CRACKED_STONE_TILES = blockItem(ADBlocks.CRACKED_STONE_TILES);
    public static final Item CRACKED_STONE_TILE_SLAB = blockItem(ADBlocks.CRACKED_STONE_TILE_SLAB);
    public static final Item CRACKED_STONE_TILE_STAIRS = blockItem(ADBlocks.CRACKED_STONE_TILE_STAIRS);
    public static final Item CRACKED_STONE_TILE_WALL = blockItem(ADBlocks.CRACKED_STONE_TILE_WALL);
    public static final Item SWEET_BERRY_PIE = blockItem(ADBlocks.SWEET_BERRY_PIE);
    public static final Item BLUEBERRY_PIE = blockItem(ADBlocks.BLUEBERRY_PIE);
    public static final Item BLACKSTONE_TILES = blockItem(ADBlocks.BLACKSTONE_TILES);
    public static final Item BLACKSTONE_TILE_STAIRS = blockItem(ADBlocks.BLACKSTONE_TILE_STAIRS);
    public static final Item BLACKSTONE_TILE_SLAB = blockItem(ADBlocks.BLACKSTONE_TILE_SLAB);
    public static final Item BLACKSTONE_TILE_WALL = blockItem(ADBlocks.BLACKSTONE_TILE_WALL);
    public static final Item TWISTED_BLACKSTONE_TILES = blockItem(ADBlocks.TWISTED_BLACKSTONE_TILES);
    public static final Item TWISTED_BLACKSTONE_TILE_STAIRS = blockItem(ADBlocks.TWISTED_BLACKSTONE_TILE_STAIRS);
    public static final Item TWISTED_BLACKSTONE_TILE_SLAB = blockItem(ADBlocks.TWISTED_BLACKSTONE_TILE_SLAB);
    public static final Item TWISTED_BLACKSTONE_TILE_WALL = blockItem(ADBlocks.TWISTED_BLACKSTONE_TILE_WALL);
    public static final Item WEEPING_BLACKSTONE_TILES = blockItem(ADBlocks.WEEPING_BLACKSTONE_TILES);
    public static final Item WEEPING_BLACKSTONE_TILE_STAIRS = blockItem(ADBlocks.WEEPING_BLACKSTONE_TILE_STAIRS);
    public static final Item WEEPING_BLACKSTONE_TILE_SLAB = blockItem(ADBlocks.WEEPING_BLACKSTONE_TILE_SLAB);
    public static final Item WEEPING_BLACKSTONE_TILE_WALL = blockItem(ADBlocks.WEEPING_BLACKSTONE_TILE_WALL);
    public static final Item TWISTED_POLISHED_BLACKSTONE_BRICKS = blockItem(ADBlocks.TWISTED_POLISHED_BLACKSTONE_BRICKS);
    public static final Item TWISTED_POLISHED_BLACKSTONE_BRICK_STAIRS = blockItem(ADBlocks.TWISTED_POLISHED_BLACKSTONE_BRICK_STAIRS);
    public static final Item TWISTED_POLISHED_BLACKSTONE_BRICK_SLAB = blockItem(ADBlocks.TWISTED_POLISHED_BLACKSTONE_BRICK_SLAB);
    public static final Item TWISTED_POLISHED_BLACKSTONE_BRICK_WALL = blockItem(ADBlocks.TWISTED_POLISHED_BLACKSTONE_BRICK_WALL);
    public static final Item WEEPING_POLISHED_BLACKSTONE_BRICKS = blockItem(ADBlocks.WEEPING_POLISHED_BLACKSTONE_BRICKS);
    public static final Item WEEPING_POLISHED_BLACKSTONE_BRICK_STAIRS = blockItem(ADBlocks.WEEPING_POLISHED_BLACKSTONE_BRICK_STAIRS);
    public static final Item WEEPING_POLISHED_BLACKSTONE_BRICK_SLAB = blockItem(ADBlocks.WEEPING_POLISHED_BLACKSTONE_BRICK_SLAB);
    public static final Item WEEPING_POLISHED_BLACKSTONE_BRICK_WALL = blockItem(ADBlocks.WEEPING_POLISHED_BLACKSTONE_BRICK_WALL);
    public static final Item TWISTED_BLACKSTONE = blockItem(ADBlocks.TWISTED_BLACKSTONE);
    public static final Item TWISTED_BLACKSTONE_STAIRS = blockItem(ADBlocks.TWISTED_BLACKSTONE_STAIRS);
    public static final Item TWISTED_BLACKSTONE_SLAB = blockItem(ADBlocks.TWISTED_BLACKSTONE_SLAB);
    public static final Item TWISTED_BLACKSTONE_WALL = blockItem(ADBlocks.TWISTED_BLACKSTONE_WALL);
    public static final Item WEEPING_BLACKSTONE = blockItem(ADBlocks.WEEPING_BLACKSTONE);
    public static final Item WEEPING_BLACKSTONE_STAIRS = blockItem(ADBlocks.WEEPING_BLACKSTONE_STAIRS);
    public static final Item WEEPING_BLACKSTONE_SLAB = blockItem(ADBlocks.WEEPING_BLACKSTONE_SLAB);
    public static final Item WEEPING_BLACKSTONE_WALL = blockItem(ADBlocks.WEEPING_BLACKSTONE_WALL);
    public static final Item QUARTZ_TILES = blockItem(ADBlocks.QUARTZ_TILES);
    public static final Item QUARTZ_TILE_STAIRS = blockItem(ADBlocks.QUARTZ_TILE_STAIRS);
    public static final Item QUARTZ_TILE_SLAB = blockItem(ADBlocks.QUARTZ_TILE_SLAB);
    public static final Item QUARTZ_TILE_WALL = blockItem(ADBlocks.QUARTZ_TILE_WALL);
    public static final Item CALCITE_BRICKS = blockItem(ADBlocks.CALCITE_BRICKS);
    public static final Item CALCITE_BRICK_STAIRS = blockItem(ADBlocks.CALCITE_BRICK_STAIRS);
    public static final Item CALCITE_BRICK_SLAB = blockItem(ADBlocks.CALCITE_BRICK_SLAB);
    public static final Item CALCITE_BRICK_WALL = blockItem(ADBlocks.CALCITE_BRICK_WALL);
    public static final Item MOSSY_CALCITE_BRICKS = blockItem(ADBlocks.MOSSY_CALCITE_BRICKS);
    public static final Item MOSSY_CALCITE_BRICK_STAIRS = blockItem(ADBlocks.MOSSY_CALCITE_BRICK_STAIRS);
    public static final Item MOSSY_CALCITE_BRICK_SLAB = blockItem(ADBlocks.MOSSY_CALCITE_BRICK_SLAB);
    public static final Item MOSSY_CALCITE_BRICK_WALL = blockItem(ADBlocks.MOSSY_CALCITE_BRICK_WALL);
    public static final Item CRACKED_CALCITE_BRICKS = blockItem(ADBlocks.CRACKED_CALCITE_BRICKS);
    public static final Item CRACKED_CALCITE_BRICK_STAIRS = blockItem(ADBlocks.CRACKED_CALCITE_BRICK_STAIRS);
    public static final Item CRACKED_CALCITE_BRICK_SLAB = blockItem(ADBlocks.CRACKED_CALCITE_BRICK_SLAB);
    public static final Item CRACKED_CALCITE_BRICK_WALL = blockItem(ADBlocks.CRACKED_CALCITE_BRICK_WALL);
    public static final Item CHISELED_CALCITE_BRICKS = blockItem(ADBlocks.CHISELED_CALCITE_BRICKS);
    public static final Item DRIPSTONE_BRICKS = blockItem(ADBlocks.DRIPSTONE_BRICKS);
    public static final Item DRIPSTONE_BRICK_STAIRS = blockItem(ADBlocks.DRIPSTONE_BRICK_STAIRS);
    public static final Item DRIPSTONE_BRICK_SLAB = blockItem(ADBlocks.DRIPSTONE_BRICK_SLAB);
    public static final Item DRIPSTONE_BRICK_WALL = blockItem(ADBlocks.DRIPSTONE_BRICK_WALL);
    public static final Item MOSSY_DRIPSTONE_BRICKS = blockItem(ADBlocks.MOSSY_DRIPSTONE_BRICKS);
    public static final Item MOSSY_DRIPSTONE_BRICK_STAIRS = blockItem(ADBlocks.MOSSY_DRIPSTONE_BRICK_STAIRS);
    public static final Item MOSSY_DRIPSTONE_BRICK_SLAB = blockItem(ADBlocks.MOSSY_DRIPSTONE_BRICK_SLAB);
    public static final Item MOSSY_DRIPSTONE_BRICK_WALL = blockItem(ADBlocks.MOSSY_DRIPSTONE_BRICK_WALL);
    public static final Item CRACKED_DRIPSTONE_BRICKS = blockItem(ADBlocks.CRACKED_DRIPSTONE_BRICKS);
    public static final Item CRACKED_DRIPSTONE_BRICK_STAIRS = blockItem(ADBlocks.CRACKED_DRIPSTONE_BRICK_STAIRS);
    public static final Item CRACKED_DRIPSTONE_BRICK_SLAB = blockItem(ADBlocks.CRACKED_DRIPSTONE_BRICK_SLAB);
    public static final Item CRACKED_DRIPSTONE_BRICK_WALL = blockItem(ADBlocks.CRACKED_DRIPSTONE_BRICK_WALL);
    public static final Item CHISELED_DRIPSTONE_BRICKS = blockItem(ADBlocks.CHISELED_DRIPSTONE_BRICKS);
    public static final Item GREEN_ONION = new AliasedBlockItem(ADBlocks.GREEN_ONIONS, new Item.Settings()
            .food(ADFoodComponents.GREEN_ONION));
    public static final Item BLUEBERRIES = new AliasedBlockItem(ADBlocks.BLUEBERRY_BUSH, new Item.Settings()
            .food(ADFoodComponents.BLUEBERRIES));
    public static final Item SWEET_BERRY_JUICE = new ADDrinkContainerItem(new Item.Settings()
            .food(ADFoodComponents.SWEET_BERRY_JUICE).maxCount(16));
    public static final Item BLUEBERRY_JUICE = new ADDrinkContainerItem(new Item.Settings()
            .food(ADFoodComponents.BLUEBERRY_JUICE).maxCount(16));
    public static final Item NOODLES = item();
    public static final Item NOODLE_SOUP = new ADFoodContainerItem(new Item.Settings()
            .food(ADFoodComponents.NOODLE_SOUP).maxCount(1));
    public static final Item PUDDING = new ADFoodContainerItem(new Item.Settings()
            .food(ADFoodComponents.PUDDING).maxCount(1));
    public static final Item BERRY_PUDDING = new ADFoodContainerItem(new Item.Settings()
            .food(ADFoodComponents.BERRY_PUDDING).maxCount(1));
    public static final Item SMOKY_QUARTZ = item();
    public static final Item CARAMEL_APPLE = new ADFoodContainerItem(new Item.Settings()
            .food(ADFoodComponents.CARAMEL_APPLE).maxCount(1), Items.STICK);
    public static final Item CARAMEL = item();
    public static final Item SPRUCE_CONE = new Item(new Item.Settings().food(ADFoodComponents.SPRUCE_CONE));
    public static final Item FORESTS_BOUNTY = new ADFoodContainerItem(new Item.Settings()
            .food(ADFoodComponents.FORESTS_BOUNTY).maxCount(1));
    public static final Item WITCHS_CRADLE_BRANCH = new AliasedBlockItem(ADBlocks.WITCHS_CRADLE, new Item.Settings()
            .food(ADFoodComponents.WITCHS_CRADLE_BRANCH));
    public static final Item WITCHS_CRADLE_SOUP = new ADFoodContainerItem(new Item.Settings()
            .food(ADFoodComponents.WITCHS_CRADLE_SOUP).maxCount(1));
    public static final Item MIXED_SEED_PACKET = new ADMixedSeedPacketItem(new Item.Settings());
    public static final Item CATTAIL = new AliasedBlockItem(ADBlocks.CATTAIL, new Item.Settings());
    public static final Item FRIED_EGG = new Item(new Item.Settings().food(ADFoodComponents.FRIED_EGG).maxCount(16));
    public static final Item BLOOD_KELP_SEED_CLUSTER = new AliasedBlockItem(ADBlocks.BLOOD_KELP, new Item.Settings());
    public static final Item BLOOD_KELP = item();
    public static final Item DRIED_BLOOD_KELP_BLOCK = blockItem(ADBlocks.DRIED_BLOOD_KELP_BLOCK);
    public static final Item DRIED_BLOOD_KELP = new Item(new Item.Settings().food(FoodComponents.DRIED_KELP));
    public static final Item BLOOD_KELP_LANTERN = blockItem(ADBlocks.BLOOD_KELP_LANTERN);
    public static final Item MAROON_WOOL = blockItem(ADBlocks.MAROON_WOOL);
    public static final Item MAROON_STAINED_GLASS = blockItem(ADBlocks.MAROON_STAINED_GLASS);
    public static final Item MAROON_STAINED_GLASS_PANE = blockItem(ADBlocks.MAROON_STAINED_GLASS_PANE);
    public static final Item MAROON_CANDLE = blockItem(ADBlocks.MAROON_CANDLE);
    public static final Item MAROON_CONCRETE = blockItem(ADBlocks.MAROON_CONCRETE);
    public static final Item MAROON_CONCRETE_POWDER = blockItem(ADBlocks.MAROON_CONCRETE_POWDER);
    public static final Item MAROON_DYE = item();
    public static final Item HOGLIN_STEW = new ADFoodContainerItem(new Item.Settings()
            .food(ADFoodComponents.HOGLIN_STEW).maxCount(1));
    public static final Item WEEPING_HEART_NECTAR_BUCKET = new ADDrinkContainerItem(new Item.Settings()
            .food(ADFoodComponents.WEEPING_HEART_NECTAR_BUCKET).maxCount(1).recipeRemainder(Items.BUCKET), Items.BUCKET);
    public static final Item WEEPING_HEART_SEEDS = new AliasedBlockItem(ADBlocks.WEEPING_HEART, new Item.Settings());
    public static final Item CAMEL_PLUSH = blockItem(ADBlocks.CAMEL_PLUSH);
    public static final Item CINDERSNAP_BERRIES = new AliasedBlockItem(ADBlocks.CINDERSNAP_BERRY_BUSH, new Item.Settings()
            .food(ADFoodComponents.NETHER_BERRIES));
    public static final Item FROSTBITE_BERRIES = new AliasedBlockItem(ADBlocks.FROSTBITE_BERRY_BUSH, new Item.Settings()
            .food(ADFoodComponents.NETHER_BERRIES));
    public static final Item POLISHED_DRIPSTONE = blockItem(ADBlocks.POLISHED_DRIPSTONE);
    public static final Item POLISHED_DRIPSTONE_STAIRS = blockItem(ADBlocks.POLISHED_DRIPSTONE_STAIRS);
    public static final Item POLISHED_DRIPSTONE_SLAB = blockItem(ADBlocks.POLISHED_DRIPSTONE_SLAB);
    public static final Item POLISHED_DRIPSTONE_WALL = blockItem(ADBlocks.POLISHED_DRIPSTONE_WALL);
    public static final Item POLISHED_CALCITE = blockItem(ADBlocks.POLISHED_CALCITE);
    public static final Item POLISHED_CALCITE_STAIRS = blockItem(ADBlocks.POLISHED_CALCITE_STAIRS);
    public static final Item POLISHED_CALCITE_SLAB = blockItem(ADBlocks.POLISHED_CALCITE_SLAB);
    public static final Item POLISHED_CALCITE_WALL = blockItem(ADBlocks.POLISHED_CALCITE_WALL);
    public static final Item DRIPSTONE_STAIRS = blockItem(ADBlocks.DRIPSTONE_STAIRS);
    public static final Item DRIPSTONE_SLAB = blockItem(ADBlocks.DRIPSTONE_SLAB);
    public static final Item DRIPSTONE_WALL = blockItem(ADBlocks.DRIPSTONE_WALL);
    public static final Item CALCITE_STAIRS = blockItem(ADBlocks.CALCITE_STAIRS);
    public static final Item CALCITE_SLAB = blockItem(ADBlocks.CALCITE_SLAB);
    public static final Item CALCITE_WALL = blockItem(ADBlocks.CALCITE_WALL);
    public static final Item BAMBOO_PLANTER_BOX = blockItem(ADBlocks.BAMBOO_PLANTER_BOX);

    private static Item item() {
        return new Item(new Item.Settings());
    }

    private static Item blockItem(Block block) {
        return new BlockItem(block, new Item.Settings());
    }

    private static Item wallStandingBlockItem(Block standingBlock, Block wallBlock) {
        return new VerticallyAttachableBlockItem(standingBlock, wallBlock, new Item.Settings(), Direction.DOWN);
    }

    private static Item ropeLadderBlockItem(Block block) {
        return new ADRopeLadderBlockItem(block, new Item.Settings());
    }

    private static void registerItem(String path, Item item) {
        Registry.register(Registries.ITEM, ADReference.makeModId(path), item);
    }

    /**
     * Called during mod initialization to register every item.
     */
    public static void registerItems() {
        registerItem("bat_plush", BAT_PLUSH);
        registerItem("blaze_plush", BLAZE_PLUSH);
        registerItem("cave_spider_plush", CAVE_SPIDER_PLUSH);
        registerItem("chicken_plush", CHICKEN_PLUSH);
        registerItem("cow_plush", COW_PLUSH);
        registerItem("creeper_plush", CREEPER_PLUSH);
        registerItem("enderman_plush", ENDERMAN_PLUSH);
        registerItem("ghast_plush", GHAST_PLUSH);
        registerItem("guardian_plush", GUARDIAN_PLUSH);
        registerItem("white_horse_plush", WHITE_HORSE_PLUSH);
        registerItem("gray_horse_plush", GRAY_HORSE_PLUSH);
        registerItem("light_gray_horse_plush", LIGHT_GRAY_HORSE_PLUSH);
        registerItem("brown_horse_plush", BROWN_HORSE_PLUSH);
        registerItem("black_horse_plush", BLACK_HORSE_PLUSH);
        registerItem("magma_cube_plush", MAGMA_CUBE_PLUSH);
        registerItem("red_mooshroom_plush", RED_MOOSHROOM_PLUSH);
        registerItem("brown_mooshroom_plush", BROWN_MOOSHROOM_PLUSH);
        registerItem("ocelot_plush", OCELOT_PLUSH);
        registerItem("tabby_cat_plush", TABBY_CAT_PLUSH);
        registerItem("tuxedo_cat_plush", TUXEDO_CAT_PLUSH);
        registerItem("red_cat_plush", RED_CAT_PLUSH);
        registerItem("siamese_cat_plush", SIAMESE_CAT_PLUSH);
        registerItem("british_shorthair_cat_plush", BRITISH_SHORTHAIR_CAT_PLUSH);
        registerItem("calico_cat_plush", CALICO_CAT_PLUSH);
        registerItem("persian_cat_plush", PERSIAN_CAT_PLUSH);
        registerItem("ragdoll_cat_plush", RAGDOLL_CAT_PLUSH);
        registerItem("white_cat_plush", WHITE_CAT_PLUSH);
        registerItem("jellie_cat_plush", JELLIE_CAT_PLUSH);
        registerItem("black_cat_plush", BLACK_CAT_PLUSH);
        registerItem("pig_plush", PIG_PLUSH);
        registerItem("brown_rabbit_plush", BROWN_RABBIT_PLUSH);
        registerItem("white_rabbit_plush", WHITE_RABBIT_PLUSH);
        registerItem("black_rabbit_plush", BLACK_RABBIT_PLUSH);
        registerItem("white_splotched_rabbit_plush", WHITE_SPLOTCHED_RABBIT_PLUSH);
        registerItem("gold_rabbit_plush", GOLD_RABBIT_PLUSH);
        registerItem("toast_rabbit_plush", TOAST_RABBIT_PLUSH);
        registerItem("salt_rabbit_plush", SALT_RABBIT_PLUSH);
        registerItem("white_sheep_plush", WHITE_SHEEP_PLUSH);
        registerItem("orange_sheep_plush", ORANGE_SHEEP_PLUSH);
        registerItem("magenta_sheep_plush", MAGENTA_SHEEP_PLUSH);
        registerItem("light_blue_sheep_plush", LIGHT_BLUE_SHEEP_PLUSH);
        registerItem("yellow_sheep_plush", YELLOW_SHEEP_PLUSH);
        registerItem("lime_sheep_plush", LIME_SHEEP_PLUSH);
        registerItem("pink_sheep_plush", PINK_SHEEP_PLUSH);
        registerItem("gray_sheep_plush", GRAY_SHEEP_PLUSH);
        registerItem("light_gray_sheep_plush", LIGHT_GRAY_SHEEP_PLUSH);
        registerItem("cyan_sheep_plush", CYAN_SHEEP_PLUSH);
        registerItem("purple_sheep_plush", PURPLE_SHEEP_PLUSH);
        registerItem("blue_sheep_plush", BLUE_SHEEP_PLUSH);
        registerItem("brown_sheep_plush", BROWN_SHEEP_PLUSH);
        registerItem("green_sheep_plush", GREEN_SHEEP_PLUSH);
        registerItem("red_sheep_plush", RED_SHEEP_PLUSH);
        registerItem("black_sheep_plush", BLACK_SHEEP_PLUSH);
        registerItem("maroon_sheep_plush", MAROON_SHEEP_PLUSH);
        registerItem("skeleton_plush", SKELETON_PLUSH);
        registerItem("slime_plush", SLIME_PLUSH);
        registerItem("spider_plush", SPIDER_PLUSH);
        registerItem("squid_plush", SQUID_PLUSH);
        registerItem("glow_squid_plush", GLOW_SQUID_PLUSH);
        registerItem("bee_plush", BEE_PLUSH);
        registerItem("plains_villager_plush", PLAINS_VILLAGER_PLUSH);
        registerItem("desert_villager_plush", DESERT_VILLAGER_PLUSH);
        registerItem("jungle_villager_plush", JUNGLE_VILLAGER_PLUSH);
        registerItem("savanna_villager_plush", SAVANNA_VILLAGER_PLUSH);
        registerItem("snow_villager_plush", SNOW_VILLAGER_PLUSH);
        registerItem("swamp_villager_plush", SWAMP_VILLAGER_PLUSH);
        registerItem("taiga_villager_plush", TAIGA_VILLAGER_PLUSH);
        registerItem("crimson_villager_plush", CRIMSON_VILLAGER_PLUSH);
        registerItem("warped_villager_plush", WARPED_VILLAGER_PLUSH);
        registerItem("wandering_trader_plush", WANDERING_TRADER_PLUSH);
        registerItem("plains_zombie_villager_plush", PLAINS_ZOMBIE_VILLAGER_PLUSH);
        registerItem("desert_zombie_villager_plush", DESERT_ZOMBIE_VILLAGER_PLUSH);
        registerItem("jungle_zombie_villager_plush", JUNGLE_ZOMBIE_VILLAGER_PLUSH);
        registerItem("savanna_zombie_villager_plush", SAVANNA_ZOMBIE_VILLAGER_PLUSH);
        registerItem("snow_zombie_villager_plush", SNOW_ZOMBIE_VILLAGER_PLUSH);
        registerItem("swamp_zombie_villager_plush", SWAMP_ZOMBIE_VILLAGER_PLUSH);
        registerItem("taiga_zombie_villager_plush", TAIGA_ZOMBIE_VILLAGER_PLUSH);
        registerItem("crimson_zombie_villager_plush", CRIMSON_ZOMBIE_VILLAGER_PLUSH);
        registerItem("warped_zombie_villager_plush", WARPED_ZOMBIE_VILLAGER_PLUSH);
        registerItem("witch_plush", WITCH_PLUSH);
        registerItem("wolf_plush", WOLF_PLUSH);
        registerItem("zombie_plush", ZOMBIE_PLUSH);
        registerItem("piglin_plush", PIGLIN_PLUSH);
        registerItem("zombified_piglin_plush", ZOMBIFIED_PIGLIN_PLUSH);
        registerItem("pufferfish_plush", PUFFERFISH_PLUSH);
        registerItem("wither_plush", WITHER_PLUSH);
        registerItem("strider_plush", STRIDER_PLUSH);
        registerItem("shivering_strider_plush", SHIVERING_STRIDER_PLUSH);
        registerItem("phantom_plush", PHANTOM_PLUSH);
        registerItem("hoglin_plush", HOGLIN_PLUSH);
        registerItem("zoglin_plush", ZOGLIN_PLUSH);
        registerItem("polar_bear_plush", POLAR_BEAR_PLUSH);
        registerItem("allay_plush", ALLAY_PLUSH);
        registerItem("pillager_plush", PILLAGER_PLUSH);
        registerItem("vindicator_plush", VINDICATOR_PLUSH);
        registerItem("evoker_plush", EVOKER_PLUSH);
        registerItem("ravager_plush", RAVAGER_PLUSH);
        registerItem("shulker_plush", SHULKER_PLUSH);
        registerItem("vex_plush", VEX_PLUSH);
        registerItem("nether_smoky_quartz_ore", NETHER_SMOKY_QUARTZ_ORE);
        registerItem("smoky_quartz_block", SMOKY_QUARTZ_BLOCK);
        registerItem("chiseled_smoky_quartz_block", CHISELED_SMOKY_QUARTZ_BLOCK);
        registerItem("smoky_quartz_bricks", SMOKY_QUARTZ_BRICKS);
        registerItem("smoky_quartz_brick_stairs", SMOKY_QUARTZ_BRICK_STAIRS);
        registerItem("smoky_quartz_brick_slab", SMOKY_QUARTZ_BRICK_SLAB);
        registerItem("smoky_quartz_brick_wall", SMOKY_QUARTZ_BRICK_WALL);
        registerItem("smoky_quartz_pillar", SMOKY_QUARTZ_PILLAR);
        registerItem("smoky_quartz_stairs", SMOKY_QUARTZ_STAIRS);
        registerItem("smoky_quartz_slab", SMOKY_QUARTZ_SLAB);
        registerItem("smoky_quartz_wall", SMOKY_QUARTZ_WALL);
        registerItem("smooth_smoky_quartz", SMOOTH_SMOKY_QUARTZ);
        registerItem("smooth_smoky_quartz_stairs", SMOOTH_SMOKY_QUARTZ_STAIRS);
        registerItem("smooth_smoky_quartz_slab", SMOOTH_SMOKY_QUARTZ_SLAB);
        registerItem("smooth_smoky_quartz_wall", SMOOTH_SMOKY_QUARTZ_WALL);
        registerItem("cracked_stone_brick_stairs", CRACKED_STONE_BRICK_STAIRS);
        registerItem("cracked_stone_brick_slab", CRACKED_STONE_BRICK_SLAB);
        registerItem("cracked_stone_brick_wall", CRACKED_STONE_BRICK_WALL);
        registerItem("oak_planter_box", OAK_PLANTER_BOX);
        registerItem("spruce_planter_box", SPRUCE_PLANTER_BOX);
        registerItem("birch_planter_box", BIRCH_PLANTER_BOX);
        registerItem("jungle_planter_box", JUNGLE_PLANTER_BOX);
        registerItem("acacia_planter_box", ACACIA_PLANTER_BOX);
        registerItem("dark_oak_planter_box", DARK_OAK_PLANTER_BOX);
        registerItem("mangrove_planter_box", MANGROVE_PLANTER_BOX);
        registerItem("cherry_planter_box", CHERRY_PLANTER_BOX);
        registerItem("crimson_planter_box", CRIMSON_PLANTER_BOX);
        registerItem("warped_planter_box", WARPED_PLANTER_BOX);
        registerItem("oak_wall", OAK_WALL);
        registerItem("spruce_wall", SPRUCE_WALL);
        registerItem("birch_wall", BIRCH_WALL);
        registerItem("jungle_wall", JUNGLE_WALL);
        registerItem("acacia_wall", ACACIA_WALL);
        registerItem("dark_oak_wall", DARK_OAK_WALL);
        registerItem("mangrove_wall", MANGROVE_WALL);
        registerItem("crimson_wall", CRIMSON_WALL);
        registerItem("warped_wall", WARPED_WALL);
        registerItem("cherry_wall", CHERRY_WALL);
        registerItem("stripped_oak_wall", STRIPPED_OAK_WALL);
        registerItem("stripped_spruce_wall", STRIPPED_SPRUCE_WALL);
        registerItem("stripped_birch_wall", STRIPPED_BIRCH_WALL);
        registerItem("stripped_jungle_wall", STRIPPED_JUNGLE_WALL);
        registerItem("stripped_acacia_wall", STRIPPED_ACACIA_WALL);
        registerItem("stripped_dark_oak_wall", STRIPPED_DARK_OAK_WALL);
        registerItem("stripped_mangrove_wall", STRIPPED_MANGROVE_WALL);
        registerItem("stripped_crimson_wall", STRIPPED_CRIMSON_WALL);
        registerItem("stripped_warped_wall", STRIPPED_WARPED_WALL);
        registerItem("stripped_cherry_wall", STRIPPED_CHERRY_WALL);
        registerItem("oak_rope_ladder", OAK_ROPE_LADDER);
        registerItem("spruce_rope_ladder", SPRUCE_ROPE_LADDER);
        registerItem("birch_rope_ladder", BIRCH_ROPE_LADDER);
        registerItem("jungle_rope_ladder", JUNGLE_ROPE_LADDER);
        registerItem("acacia_rope_ladder", ACACIA_ROPE_LADDER);
        registerItem("dark_oak_rope_ladder", DARK_OAK_ROPE_LADDER);
        registerItem("crimson_rope_ladder", CRIMSON_ROPE_LADDER);
        registerItem("warped_rope_ladder", WARPED_ROPE_LADDER);
        registerItem("mangrove_rope_ladder", MANGROVE_ROPE_LADDER);
        registerItem("cherry_rope_ladder", CHERRY_ROPE_LADDER);
        registerItem("iron_ladder", IRON_LADDER);
        registerItem("snow_bricks", SNOW_BRICKS);
        registerItem("snow_brick_stairs", SNOW_BRICK_STAIRS);
        registerItem("snow_brick_slab", SNOW_BRICK_SLAB);
        registerItem("snow_brick_wall", SNOW_BRICK_WALL);
        registerItem("packed_snow", PACKED_SNOW);
        registerItem("packed_snow_stairs", PACKED_SNOW_STAIRS);
        registerItem("packed_snow_slab", PACKED_SNOW_SLAB);
        registerItem("packed_snow_wall", PACKED_SNOW_WALL);
        registerItem("purple_mushroom", PURPLE_MUSHROOM);
        registerItem("purple_mushroom_block", PURPLE_MUSHROOM_BLOCK);
        registerItem("woodcutter", WOODCUTTER);
        registerItem("white_campfire", WHITE_CAMPFIRE);
        registerItem("orange_campfire", ORANGE_CAMPFIRE);
        registerItem("magenta_campfire", MAGENTA_CAMPFIRE);
        registerItem("light_blue_campfire", LIGHT_BLUE_CAMPFIRE);
        registerItem("yellow_campfire", YELLOW_CAMPFIRE);
        registerItem("lime_campfire", LIME_CAMPFIRE);
        registerItem("pink_campfire", PINK_CAMPFIRE);
        registerItem("gray_campfire", GRAY_CAMPFIRE);
        registerItem("light_gray_campfire", LIGHT_GRAY_CAMPFIRE);
        registerItem("cyan_campfire", CYAN_CAMPFIRE);
        registerItem("purple_campfire", PURPLE_CAMPFIRE);
        registerItem("blue_campfire", BLUE_CAMPFIRE);
        registerItem("brown_campfire", BROWN_CAMPFIRE);
        registerItem("green_campfire", GREEN_CAMPFIRE);
        registerItem("red_campfire", RED_CAMPFIRE);
        registerItem("black_campfire", BLACK_CAMPFIRE);
        registerItem("maroon_campfire", MAROON_CAMPFIRE);
        registerItem("white_lantern", WHITE_LANTERN);
        registerItem("orange_lantern", ORANGE_LANTERN);
        registerItem("magenta_lantern", MAGENTA_LANTERN);
        registerItem("light_blue_lantern", LIGHT_BLUE_LANTERN);
        registerItem("yellow_lantern", YELLOW_LANTERN);
        registerItem("lime_lantern", LIME_LANTERN);
        registerItem("pink_lantern", PINK_LANTERN);
        registerItem("gray_lantern", GRAY_LANTERN);
        registerItem("light_gray_lantern", LIGHT_GRAY_LANTERN);
        registerItem("cyan_lantern", CYAN_LANTERN);
        registerItem("purple_lantern", PURPLE_LANTERN);
        registerItem("blue_lantern", BLUE_LANTERN);
        registerItem("brown_lantern", BROWN_LANTERN);
        registerItem("green_lantern", GREEN_LANTERN);
        registerItem("red_lantern", RED_LANTERN);
        registerItem("black_lantern", BLACK_LANTERN);
        registerItem("maroon_lantern", MAROON_LANTERN);
        registerItem("white_torch", WHITE_TORCH);
        registerItem("orange_torch", ORANGE_TORCH);
        registerItem("magenta_torch", MAGENTA_TORCH);
        registerItem("light_blue_torch", LIGHT_BLUE_TORCH);
        registerItem("yellow_torch", YELLOW_TORCH);
        registerItem("lime_torch", LIME_TORCH);
        registerItem("pink_torch", PINK_TORCH);
        registerItem("gray_torch", GRAY_TORCH);
        registerItem("light_gray_torch", LIGHT_GRAY_TORCH);
        registerItem("cyan_torch", CYAN_TORCH);
        registerItem("purple_torch", PURPLE_TORCH);
        registerItem("blue_torch", BLUE_TORCH);
        registerItem("brown_torch", BROWN_TORCH);
        registerItem("green_torch", GREEN_TORCH);
        registerItem("red_torch", RED_TORCH);
        registerItem("black_torch", BLACK_TORCH);
        registerItem("maroon_torch", MAROON_TORCH);
        registerItem("bauxite", BAUXITE);
        registerItem("bauxite_slab", BAUXITE_SLAB);
        registerItem("bauxite_stairs", BAUXITE_STAIRS);
        registerItem("bauxite_wall", BAUXITE_WALL);
        registerItem("bauxite_bricks", BAUXITE_BRICKS);
        registerItem("bauxite_brick_stairs", BAUXITE_BRICK_STAIRS);
        registerItem("bauxite_brick_slab", BAUXITE_BRICK_SLAB);
        registerItem("bauxite_brick_wall", BAUXITE_BRICK_WALL);
        registerItem("mossy_bauxite_bricks", MOSSY_BAUXITE_BRICKS);
        registerItem("mossy_bauxite_brick_stairs", MOSSY_BAUXITE_BRICK_STAIRS);
        registerItem("mossy_bauxite_brick_slab", MOSSY_BAUXITE_BRICK_SLAB);
        registerItem("mossy_bauxite_brick_wall", MOSSY_BAUXITE_BRICK_WALL);
        registerItem("cracked_bauxite_bricks", CRACKED_BAUXITE_BRICKS);
        registerItem("cracked_bauxite_brick_stairs", CRACKED_BAUXITE_BRICK_STAIRS);
        registerItem("cracked_bauxite_brick_slab", CRACKED_BAUXITE_BRICK_SLAB);
        registerItem("cracked_bauxite_brick_wall", CRACKED_BAUXITE_BRICK_WALL);
        registerItem("twisted_nether_bricks", TWISTED_NETHER_BRICKS);
        registerItem("twisted_nether_brick_stairs", TWISTED_NETHER_BRICK_STAIRS);
        registerItem("twisted_nether_brick_slab", TWISTED_NETHER_BRICK_SLAB);
        registerItem("twisted_nether_brick_wall", TWISTED_NETHER_BRICK_WALL);
        registerItem("twisted_netherrack", TWISTED_NETHERRACK);
        registerItem("twisted_netherrack_stairs", TWISTED_NETHERRACK_STAIRS);
        registerItem("twisted_netherrack_slab", TWISTED_NETHERRACK_SLAB);
        registerItem("twisted_netherrack_wall", TWISTED_NETHERRACK_WALL);
        registerItem("weeping_nether_bricks", WEEPING_NETHER_BRICKS);
        registerItem("weeping_nether_brick_stairs", WEEPING_NETHER_BRICK_STAIRS);
        registerItem("weeping_nether_brick_slab", WEEPING_NETHER_BRICK_SLAB);
        registerItem("weeping_nether_brick_wall", WEEPING_NETHER_BRICK_WALL);
        registerItem("weeping_netherrack", WEEPING_NETHERRACK);
        registerItem("weeping_netherrack_stairs", WEEPING_NETHERRACK_STAIRS);
        registerItem("weeping_netherrack_slab", WEEPING_NETHERRACK_SLAB);
        registerItem("weeping_netherrack_wall", WEEPING_NETHERRACK_WALL);
        registerItem("snapdragon", SNAPDRAGON);
        registerItem("ender_grass", ENDER_GRASS);
        registerItem("icicle", ICICLE);
        registerItem("chocolate_cake", CHOCOLATE_CAKE);
        registerItem("red_velvet_cake", RED_VELVET_CAKE);
        registerItem("stone_tiles", STONE_TILES);
        registerItem("stone_tile_slab", STONE_TILE_SLAB);
        registerItem("stone_tile_stairs", STONE_TILE_STAIRS);
        registerItem("stone_tile_wall", STONE_TILE_WALL);
        registerItem("mossy_stone_tiles", MOSSY_STONE_TILES);
        registerItem("mossy_stone_tile_slab", MOSSY_STONE_TILE_SLAB);
        registerItem("mossy_stone_tile_stairs", MOSSY_STONE_TILE_STAIRS);
        registerItem("mossy_stone_tile_wall", MOSSY_STONE_TILE_WALL);
        registerItem("cracked_stone_tiles", CRACKED_STONE_TILES);
        registerItem("cracked_stone_tile_slab", CRACKED_STONE_TILE_SLAB);
        registerItem("cracked_stone_tile_stairs", CRACKED_STONE_TILE_STAIRS);
        registerItem("cracked_stone_tile_wall", CRACKED_STONE_TILE_WALL);
        registerItem("sweet_berry_pie", SWEET_BERRY_PIE);
        registerItem("blueberry_pie", BLUEBERRY_PIE);
        registerItem("blackstone_tiles", BLACKSTONE_TILES);
        registerItem("blackstone_tile_stairs", BLACKSTONE_TILE_STAIRS);
        registerItem("blackstone_tile_slab", BLACKSTONE_TILE_SLAB);
        registerItem("blackstone_tile_wall", BLACKSTONE_TILE_WALL);
        registerItem("twisted_blackstone_tiles", TWISTED_BLACKSTONE_TILES);
        registerItem("twisted_blackstone_tile_stairs", TWISTED_BLACKSTONE_TILE_STAIRS);
        registerItem("twisted_blackstone_tile_slab", TWISTED_BLACKSTONE_TILE_SLAB);
        registerItem("twisted_blackstone_tile_wall", TWISTED_BLACKSTONE_TILE_WALL);
        registerItem("weeping_blackstone_tiles", WEEPING_BLACKSTONE_TILES);
        registerItem("weeping_blackstone_tile_stairs", WEEPING_BLACKSTONE_TILE_STAIRS);
        registerItem("weeping_blackstone_tile_slab", WEEPING_BLACKSTONE_TILE_SLAB);
        registerItem("weeping_blackstone_tile_wall", WEEPING_BLACKSTONE_TILE_WALL);
        registerItem("twisted_polished_blackstone_bricks", TWISTED_POLISHED_BLACKSTONE_BRICKS);
        registerItem("twisted_polished_blackstone_brick_stairs", TWISTED_POLISHED_BLACKSTONE_BRICK_STAIRS);
        registerItem("twisted_polished_blackstone_brick_slab", TWISTED_POLISHED_BLACKSTONE_BRICK_SLAB);
        registerItem("twisted_polished_blackstone_brick_wall", TWISTED_POLISHED_BLACKSTONE_BRICK_WALL);
        registerItem("weeping_polished_blackstone_bricks", WEEPING_POLISHED_BLACKSTONE_BRICKS);
        registerItem("weeping_polished_blackstone_brick_stairs", WEEPING_POLISHED_BLACKSTONE_BRICK_STAIRS);
        registerItem("weeping_polished_blackstone_brick_slab", WEEPING_POLISHED_BLACKSTONE_BRICK_SLAB);
        registerItem("weeping_polished_blackstone_brick_wall", WEEPING_POLISHED_BLACKSTONE_BRICK_WALL);
        registerItem("twisted_blackstone", TWISTED_BLACKSTONE);
        registerItem("twisted_blackstone_stairs", TWISTED_BLACKSTONE_STAIRS);
        registerItem("twisted_blackstone_slab", TWISTED_BLACKSTONE_SLAB);
        registerItem("twisted_blackstone_wall", TWISTED_BLACKSTONE_WALL);
        registerItem("weeping_blackstone", WEEPING_BLACKSTONE);
        registerItem("weeping_blackstone_stairs", WEEPING_BLACKSTONE_STAIRS);
        registerItem("weeping_blackstone_slab", WEEPING_BLACKSTONE_SLAB);
        registerItem("weeping_blackstone_wall", WEEPING_BLACKSTONE_WALL);
        registerItem("quartz_tiles", QUARTZ_TILES);
        registerItem("quartz_tile_stairs", QUARTZ_TILE_STAIRS);
        registerItem("quartz_tile_slab", QUARTZ_TILE_SLAB);
        registerItem("quartz_tile_wall", QUARTZ_TILE_WALL);
        registerItem("calcite_bricks", CALCITE_BRICKS);
        registerItem("calcite_brick_stairs", CALCITE_BRICK_STAIRS);
        registerItem("calcite_brick_slab", CALCITE_BRICK_SLAB);
        registerItem("calcite_brick_wall", CALCITE_BRICK_WALL);
        registerItem("mossy_calcite_bricks", MOSSY_CALCITE_BRICKS);
        registerItem("mossy_calcite_brick_stairs", MOSSY_CALCITE_BRICK_STAIRS);
        registerItem("mossy_calcite_brick_slab", MOSSY_CALCITE_BRICK_SLAB);
        registerItem("mossy_calcite_brick_wall", MOSSY_CALCITE_BRICK_WALL);
        registerItem("cracked_calcite_bricks", CRACKED_CALCITE_BRICKS);
        registerItem("cracked_calcite_brick_stairs", CRACKED_CALCITE_BRICK_STAIRS);
        registerItem("cracked_calcite_brick_slab", CRACKED_CALCITE_BRICK_SLAB);
        registerItem("cracked_calcite_brick_wall", CRACKED_CALCITE_BRICK_WALL);
        registerItem("chiseled_calcite_bricks", CHISELED_CALCITE_BRICKS);
        registerItem("dripstone_bricks", DRIPSTONE_BRICKS);
        registerItem("dripstone_brick_stairs", DRIPSTONE_BRICK_STAIRS);
        registerItem("dripstone_brick_slab", DRIPSTONE_BRICK_SLAB);
        registerItem("dripstone_brick_wall", DRIPSTONE_BRICK_WALL);
        registerItem("mossy_dripstone_bricks", MOSSY_DRIPSTONE_BRICKS);
        registerItem("mossy_dripstone_brick_stairs", MOSSY_DRIPSTONE_BRICK_STAIRS);
        registerItem("mossy_dripstone_brick_slab", MOSSY_DRIPSTONE_BRICK_SLAB);
        registerItem("mossy_dripstone_brick_wall", MOSSY_DRIPSTONE_BRICK_WALL);
        registerItem("cracked_dripstone_bricks", CRACKED_DRIPSTONE_BRICKS);
        registerItem("cracked_dripstone_brick_stairs", CRACKED_DRIPSTONE_BRICK_STAIRS);
        registerItem("cracked_dripstone_brick_slab", CRACKED_DRIPSTONE_BRICK_SLAB);
        registerItem("cracked_dripstone_brick_wall", CRACKED_DRIPSTONE_BRICK_WALL);
        registerItem("chiseled_dripstone_bricks", CHISELED_DRIPSTONE_BRICKS);
        registerItem("green_onion", GREEN_ONION);
        registerItem("blueberries", BLUEBERRIES);
        registerItem("sweet_berry_juice", SWEET_BERRY_JUICE);
        registerItem("blueberry_juice", BLUEBERRY_JUICE);
        registerItem("noodles", NOODLES);
        registerItem("noodle_soup", NOODLE_SOUP);
        registerItem("pudding", PUDDING);
        registerItem("berry_pudding", BERRY_PUDDING);
        registerItem("smoky_quartz", SMOKY_QUARTZ);
        registerItem("caramel_apple", CARAMEL_APPLE);
        registerItem("caramel", CARAMEL);
        registerItem("spruce_cone", SPRUCE_CONE);
        registerItem("forests_bounty", FORESTS_BOUNTY);
        registerItem("witchs_cradle_branch", WITCHS_CRADLE_BRANCH);
        registerItem("witchs_cradle_soup", WITCHS_CRADLE_SOUP);
        registerItem("mixed_seed_packet", MIXED_SEED_PACKET);
        registerItem("cattail", CATTAIL);
        registerItem("fried_egg", FRIED_EGG);
        registerItem("blood_kelp_seed_cluster", BLOOD_KELP_SEED_CLUSTER);
        registerItem("blood_kelp", BLOOD_KELP);
        registerItem("dried_blood_kelp_block", DRIED_BLOOD_KELP_BLOCK);
        registerItem("dried_blood_kelp", DRIED_BLOOD_KELP);
        registerItem("blood_kelp_lantern", BLOOD_KELP_LANTERN);
        registerItem("maroon_wool", MAROON_WOOL);
        registerItem("maroon_stained_glass", MAROON_STAINED_GLASS);
        registerItem("maroon_stained_glass_pane", MAROON_STAINED_GLASS_PANE);
        registerItem("maroon_candle", MAROON_CANDLE);
        registerItem("maroon_concrete", MAROON_CONCRETE);
        registerItem("maroon_concrete_powder", MAROON_CONCRETE_POWDER);
        registerItem("maroon_dye", MAROON_DYE);
        registerItem("hoglin_stew", HOGLIN_STEW);
        registerItem("weeping_heart_nectar_bucket", WEEPING_HEART_NECTAR_BUCKET);
        registerItem("weeping_heart_seeds", WEEPING_HEART_SEEDS);
        registerItem("camel_plush", CAMEL_PLUSH);
        registerItem("cindersnap_berries", CINDERSNAP_BERRIES);
        registerItem("frostbite_berries", FROSTBITE_BERRIES);
        registerItem("polished_dripstone", POLISHED_DRIPSTONE);
        registerItem("polished_dripstone_stairs", POLISHED_DRIPSTONE_STAIRS);
        registerItem("polished_dripstone_slab", POLISHED_DRIPSTONE_SLAB);
        registerItem("polished_dripstone_wall", POLISHED_DRIPSTONE_WALL);
        registerItem("polished_calcite", POLISHED_CALCITE);
        registerItem("polished_calcite_stairs", POLISHED_CALCITE_STAIRS);
        registerItem("polished_calcite_slab", POLISHED_CALCITE_SLAB);
        registerItem("polished_calcite_wall", POLISHED_CALCITE_WALL);
        registerItem("dripstone_stairs", DRIPSTONE_STAIRS);
        registerItem("dripstone_slab", DRIPSTONE_SLAB);
        registerItem("dripstone_wall", DRIPSTONE_WALL);
        registerItem("calcite_stairs", CALCITE_STAIRS);
        registerItem("calcite_slab", CALCITE_SLAB);
        registerItem("calcite_wall", CALCITE_WALL);
        registerItem("bamboo_planter_box", BAMBOO_PLANTER_BOX);

        AssortedDiscoveries.LOGGER.info("Registered Items");
    }
}
